name: my workflow
on: workflow_dispatch
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Helllo World"
      - name: Print Goodbye
        run: echo "Bye Bye!"
